# Site settings
title: ITSail
email: info@itsail.ru
description: >- # this means to ignore newlines until "baseurl:"
  Блог об операционных системах, open source и программировании.
baseurl: "" # the subpath of your site, e.g. /blog

# the base hostname & protocol for your site, e.g. http://example.com
url: "https://blog.itsail.ru"

vk_groupname: web_itsail
twitter_username: itsail
github_username:  itsail
author: ITSail

# Build settings
markdown: kramdown
timezone: Europe/Moscow
destination: _site
relative_permalinks: false
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"


compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all

sass:
  sass_dir: assets/_sass
  style: compressed

images: '/assets/images'

exclude:
  - deploy.sh
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
